spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interviewDataBase?createDatabaseIfNotExist=true
    username: root
    password: Root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
        
  application:
    name: interview-service
server:
  port: 8181

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka