spring:
  datasource:
    url: jdbc:mysql://localhost:3306/careersuggestionDataBase?createDatabaseIfNotExist=true
    username: root
    password: Root123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    show-sql: true

  application:
    name: careersuggestion-service

server:
  port: 9193
