spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employerDataBase?createDatabaseIfNotExist=true
    username: root
    password: Root123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    show-sql: true

  application:
    name: employers

server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka